version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.4
    container_name: schools_postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password_0323
      POSTGRES_DB: schools_ke
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    container_name: schools_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password_0323@db:5432/schools_ke
      FLASK_ENV: production
      APP_SECRET: "please-change-this"
    ports:
      - "8000:8000"
    volumes:
      - .:/app:rw

volumes:
  pgdata:
    driver: local
